### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by jornj** [ExM/NMoney#1]
Hi,
any plans to implement dotnet support?

**Comment by ExM** [comment]
Maybe you meant .NET Standard?
Why not...
I'll try to add support for .Net Standard.
But if you have the opportunity to do it faster, then I will accept your request.

**Comment by ExM** [comment]
https://twitter.com/gul_banana/status/922349543781306369

**Comment by ExM** [comment]
Completed in ecce55184e846810f12b4379593b165cb937d1c5
